apiVersion: v2
name: io2-portal
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.3-rc.13

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 3.2.2

dependencies:
  - name: traefik
    version: "9.12.3"
    repository: "https://helm.traefik.io/traefik"
    condition: traefik.enabled
  - name: keda
    version: "2.3.2"
    repository: "https://kedacore.github.io/charts"
    condition: keda.enabled
  - name: cava-media
    version: "0.1.4-rc.2"
    repository: "https://cormorack.github.io/cava-media"
    condition: cava-media.enabled
  - name: cava-metadata
    version: "0.1.3-rc.2"
    repository: "https://cormorack.github.io/cava-metadata"
    condition: cava-metadata.enabled
  - name: cava-data
    version: "0.1.4-rc.1"
    repository: "https://cormorack.github.io/cava-data"
    condition: cava-data.enabled
  - name: cava-realtime
    version: "0.1.3-rc.3"
    repository: "https://cormorack.github.io/cava-realtime"
    condition: cava-realtime.enabled
  - name: cava-realtime-client
    version: "0.1.2-rc.4"
    repository: "https://cormorack.github.io/cava-realtime-client"
    condition: cava-realtime-client.enabled

icon: https://interactiveoceans.washington.edu/wp-content/uploads/2018/12/interactive-oceans-logo-symbol-only_sm.png
