# Default values for io2-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: io2-portal
fullnameOverride: io2-portal

cava-media:
  enabled: true

traefik:
  enabled: false
