# Default values for io2-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: io2-portal
fullnameOverride: io2-portal

cava-metadata:
  enabled: true

cava-media:
  enabled: true

cava-data:
  enabled: false
  # worker:
  #   keda:
  #     name: "cava-data-worker"
  #     secretTargetRef: []
  #     # Below example for rabbitmq
  #     # secretTargetRef:
  #     # - parameter: host
  #     #   name: cava-secrets
  #     #   key: rabbitmq-host
  #     #
  #     # Below example for aws sqs
  #     # secretTargetRef:
  #     # - parameter: awsAccessKeyID     # Required.
  #     #   name: cava-secrets          # Required.
  #     #   key: AWS_ACCESS_KEY_ID        # Required.
  #     # - parameter: awsSecretAccessKey # Required.
  #     #   name: cava-secrets            # Required.
  #     #   key: AWS_SECRET_ACCESS_KEY    # Required.
  #     replicas:
  #       min: 1
  #       max: 10
  #     pollingInterval: 3
  #     # Below example for rabbitmq
  #     queue:
  #       type: "rabbitmq"
  #       name: "data-queue"
  #       length: "2"
  #     # Below example for aws sqs
  #     # queue:
  #     #   type: "aws-sqs-queue"
  #     #   account_id: 123451786547
  #     #   name: "data-queue"
  #     #   length: "2"
  #     #   region: "us-west-2"

cava-realtime:
  enabled: false

cava-realtime-client:
  enabled: false

  # This should be disabled if the other setting is enabled!!
  cava-realtime:
    enabled: false

traefik:
  enabled: false

keda:
  enabled: false
  exists: false
