{{- if .Values.dataService.enabled -}}
{{- if and .Values.dataService.ingress.expose .Values.dataService.ingress.secure -}}
{{- $serviceName := default (include "io2-portal.name" .) -}}
{{- $servicePort := .Values.dataService.service.port -}}
{{- $servicePath := .Values.dataService.path -}}
# https://doc.traefik.io/traefik/providers/kubernetes-crd/#letsencrypt-support-with-the-custom-resource-definition-provider
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $serviceName }}-data-secure
  labels:
    {{- include "io2-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}-data
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`{{ $servicePath }}`)
      kind: Rule
      services:
        - name: {{ $serviceName }}-data
          port: {{ $servicePort }}
  {{- with .Values.dataService.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}