{{- $dataEnabled := index .Values "cava-data" "enabled" -}}
{{- if or .Values.keda.enabled .Values.keda.exists -}}
{{- if $dataEnabled -}}
{{- $dataWorker := index .Values "cava-data" "worker" -}}
{{- if hasKey $dataWorker "keda" -}}
{{- $dataWorkerKeda := index .Values "cava-data" "worker" "keda" -}}
{{- if $dataWorkerKeda -}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ $dataWorkerKeda.name }}-trigger-auth
  labels:
    {{- include "io2-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $dataWorkerKeda.name }}-trigger-auth
spec:
  {{- if $dataWorkerKeda.secretTargetRef }}
  secretTargetRef:
    {{- toYaml $dataWorkerKeda.secretTargetRef | nindent 4 }}
  {{- else }}
  secretTargetRef: []
  {{- end }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $dataWorkerKeda.name }}-scaledobject
  labels:
    {{- include "io2-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $dataWorkerKeda.name }}-scaledobject
spec:
  scaleTargetRef:
    name: cava-data-worker
  pollingInterval: {{ $dataWorkerKeda.pollingInterval | default 3 }}
  minReplicaCount: {{ $dataWorkerKeda.replicas.min | default 1 }}
  maxReplicaCount: {{ $dataWorkerKeda.replicas.max | default 10 }}
  triggers:
  - type: {{ $dataWorkerKeda.queue.type | default "rabbitmq" | quote }}
    {{- if eq $dataWorkerKeda.queue.type "rabbitmq" }}
    metadata:
      protocol: {{ $dataWorkerKeda.queue.protocol | default "amqp" | quote }}
      queueName: {{ $dataWorkerKeda.queue.name | default "data-queue" | quote }}
      mode: QueueLength
      value: {{ $dataWorkerKeda.queue.length | default "2" | quote }}
    {{- else if eq $dataWorkerKeda.queue.type "aws-sqs-queue" }}
    metadata:
      queueURL: {{ $dataWorkerKeda.queue.name | default "data-queue" | quote }}
      queueLength: {{ $dataWorkerKeda.queue.length | default "2" | quote }}
      awsRegion: {{ $dataWorkerKeda.queue.region | default "us-west-2" | quote }}
    {{- end }}
    authenticationRef:
      name: {{ $dataWorkerKeda.name }}-trigger-auth
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
