name: Portal Cloud Production Deployment

on:
  push:
    paths: ["deployments/**", "io2-portal/**"]
    branches:
      - production
  workflow_dispatch:

env:
  namespace: production

jobs:
  deploy:
    name: Deploy my app
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get-helm-3 | bash
      - name: Install git-crypt
        run: sudo apt-get install git-crypt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-2
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp ${{ secrets.GIT_CRYPT_KEY }} ./crypt.key
      - name: Unlock git-crypt Secrets
        run: git-crypt unlock ./crypt.key && git-crypt status

      # Linting
      - name: Update chart dependencies
        run: |
          helm dependency update ./io2-portal --namespace ${{ env.namespace }}
      - name: Lint chart's templates
        run: |
          helm lint ./io2-portal --strict --values deployments/values-${{ env.namespace }}.yaml

      # Initialize github deployment action
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.namespace }}

      - name: Set k8s context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: cavakops.k8s.local
        id: setcontext

      - name: Create namespace
        run: |
          NAMESPACE=$(kubectl get namespace ${{ env.namespace }} | grep "${{ env.namespace }}" | wc -l)
          if [ ${NAMESPACE} -eq 0 ];
          then
            echo "Namespace (${{ env.namespace }}) not found. Creating ..."
            kubectl create namespace ${{ env.namespace }}
          else
            echo "Namespace (${{ env.namespace }}) exists. Skipping creation ..."
            kubectl get namespace ${{ env.namespace }}
          fi
      
      - name: Apply secrets
        run: kubectl apply -n ${{ env.namespace }} -f deployments/secrets/cava-secrets.yaml

      - name: Check if chart is installed
        id: chart_check
        run: |
          INSTALLED=$(helm ls --namespace ${{ env.namespace }} | grep "io2-portal" | wc -l)
          echo "::set-output name=INSTALLED::$INSTALLED"

      - name: Install/Upgrade chart and await readiness
        if: success()
        run: |
          if [ ${{ steps.chart_check.outputs.INSTALLED }} -eq 0 ];
          then
            echo "io2-portal not installed. Installing ..."
            helm install io2-portal ./io2-portal --create-namespace --namespace ${{ env.namespace }} --values deployments/values-${{ env.namespace }}.yaml
          else
            echo "io2-portal installed. Upgrading ..."
            helm upgrade --namespace ${{ env.namespace }} -f deployments/values-${{ env.namespace }}.yaml io2-portal ./io2-portal
          fi

          . .ci-helpers/common
          full_${{ env.namespace }}_await


      - name: Kubernetes namespace report
        uses: jupyterhub/action-k8s-namespace-report@v1
        if: always()
        with:
          namespace: ${{ env.namespace }}

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}