name: Watch Dependencies

on:
  schedule:
    # Run every hour sharp, ref: https://crontab.guru/#0_*_*_*_*
    - cron: "0 * * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check-production-chart:
    name: ${{ matrix.service-name }}-production-chart-check
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service-name:
          - cava-media
          - cava-metadata
    steps:
      - uses: actions/checkout@v2

      # ref: https://github.com/oprypin/find-latest-tag
      - name: Find latest tag of dependency
        id: remote_chart
        uses: oprypin/find-latest-tag@v1
        with:
          repository: cormorack/${{ matrix.service-name }}
          releases-only: true

      # ref: https://github.com/jacobtomlinson/gha-read-helm-chart
      - name: Find current tag of dependency
        if: ${{ !contains(steps.remote_chart.outputs.tag, 'rc') }}
        id: local_chart
        uses: jacobtomlinson/gha-read-helm-chart@0.1.3
        with:
          path: io2-portal

      # ref: https://github.com/jacobtomlinson/gha-find-replace
      - name: Replace current with latest in Chart.yaml
        id: cava_media_replace
        if: ${{ !contains(steps.remote_chart.outputs.tag, 'rc') && matrix.service-name == 'cava-media' }}
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          include: "io2-portal/Chart.yaml"
          find: "${{ steps.local_chart.outputs.dependencies_cava-media_version }}"
          replace: "${{ steps.remote_chart.outputs.tag }}"
      - name: Replace current with latest in Chart.yaml
        id: cava_meta_replace
        if: ${{ !contains(steps.remote_chart.outputs.tag, 'rc') && matrix.service-name == 'cava-metadata' }}
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          include: "io2-portal/Chart.yaml"
          find: "${{ steps.local_chart.outputs.dependencies_cava-metadata_version }}"
          replace: "${{ steps.remote_chart.outputs.tag }}"

      # ref: https://github.com/jacobtomlinson/gha-find-replace
      - name: Git diff changes
        if: ${{ !contains(steps.remote_chart.outputs.tag, 'rc') }}
        run: |
          git --no-pager diff --color=always
      # ref: https://github.com/peter-evans/create-pull-request
      - name: Create a PR
        if: ${{ !contains(steps.remote_chart.outputs.tag, 'rc') }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          commit-message: Upgrade ${{ matrix.service-name }} chart to ${{ steps.remote_chart.outputs.tag }}
          title: Upgrade ${{ matrix.service-name }} chart to ${{ steps.remote_chart.outputs.tag }}
          reviewers: lsetiawan
          labels: chart/${{ matrix.service-name }}
          branch: upgrade-${{ matrix.service-name }}-prod
          delete-branch: true
          base: production
          body: |
            This PR upgrades the `io2-portal` chart to depend on ${{ matrix.service-name }} version `${{ steps.remote_chart.outputs.tag }}`.
  
  check-dev-chart:
    name: ${{ matrix.service-name }}-dev-chart-check
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        service-name:
          - cava-media
          - cava-metadata
    steps:
      - uses: actions/checkout@v2

      # ref: https://github.com/oprypin/find-latest-tag
      - name: Find latest tag of dependency
        id: remote_chart
        uses: oprypin/find-latest-tag@v1
        with:
          repository: cormorack/${{ matrix.service-name }}
          releases-only: false

      # ref: https://github.com/jacobtomlinson/gha-read-helm-chart
      - name: Find current tag of dependency
        id: local_chart
        uses: jacobtomlinson/gha-read-helm-chart@0.1.3
        with:
          path: io2-portal

      # ref: https://github.com/jacobtomlinson/gha-find-replace
      - name: Replace current with latest in Chart.yaml
        id: cava_media_replace
        if: ${{ matrix.service-name == 'cava-media' }}
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          include: "io2-portal/Chart.yaml"
          find: "${{ steps.local_chart.outputs.dependencies_cava-media_version }}"
          replace: "${{ steps.remote_chart.outputs.tag }}"
      - name: Replace current with latest in Chart.yaml
        id: cava_meta_replace
        if: ${{ matrix.service-name == 'cava-metadata' }}
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          include: "io2-portal/Chart.yaml"
          find: "${{ steps.local_chart.outputs.dependencies_cava-metadata_version }}"
          replace: "${{ steps.remote_chart.outputs.tag }}"

      # ref: https://github.com/jacobtomlinson/gha-find-replace
      - name: Git diff changes
        run: |
          git --no-pager diff --color=always
      # ref: https://github.com/peter-evans/create-pull-request
      - name: Create a PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          commit-message: Upgrade ${{ matrix.service-name }} chart to ${{ steps.remote_chart.outputs.tag }}
          title: Upgrade ${{ matrix.service-name }} chart to ${{ steps.remote_chart.outputs.tag }}
          reviewers: lsetiawan
          labels: chart/${{ matrix.service-name }}
          branch: upgrade-${{ matrix.service-name }}-dev
          delete-branch: true
          base: development
          body: |
            This PR upgrades the `io2-portal` chart to depend on ${{ matrix.service-name }} version `${{ steps.remote_chart.outputs.tag }}`.